name: "Format HCL files and commit them"
author: "Krzysztof Szyper <biotyk@mail.com>"
description: "GitHub Action automatically formatting all HCL files and committing fixed files back to the current branch."
inputs:
  push_changes:
    description: "Whether changes should be pushed back to the current branch."
    required: false
    default: "false"
outputs:
  files_changed:
    description: "List of formatted files."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "white"
  icon: "wind"
